name: Action
on: [push]
jobs:

  go-version:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-go@v2
      with:
        go-version: '1.15.8'
    - run: go version
    - run: go install golang.org/x/lint/golint
    - run: golint ./...
    
  go-fmt:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-go@v2
      with:
        go-version: '1.15.8'
    - run: go version
    - run: gofmt -l -d .

  go-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-go@v2
      with:
        go-version: '1.15.8'
    - run: go version
    - run: go test ./...

  go-run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-go@v2
      with:
        go-version: '1.15.8'
    - run: go version
    - run: go run .
