name: Action
on: [push]
jobs:

  go-version:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-go@v2
    - run: go version

  go-fmt:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-go@v2
    - run: ls
    - run: gofmt -l -d .

  go-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-go@v2
    - run: go test ./...

  go-run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-go@v2
    - run: go run .
